stuOnline/apps/content/urls.py
from django.urls import path
from apps.content.views import *


app_name = 'content'
urlpatterns = [
    path('uploadfile/', get_file, name='get_file'),
    path('<str:content_path>.html/', content_path, name='content_path'),
    path('getstu/', get_all_stu, name='get_stu'),
    path('getstuInfo/', get_all_stuInfo, name='get_all_stuInfo'),
    path('getwarningresult/', get_warning_result, name='get_warning_result'),
]

stuOnline/stuOnline/urls.py
from django.contrib import admin
from django.urls import path, include
# import xadmin
from apps.users.views import *
from apps.content.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('admin/', xadmin.site.urls),
    # User部分
    path('', login_redirect, name='login_redirect'),
    path('users/', include('users.urls')),
    # Content部分
    path('content/', include('content.urls')),
    # index通用访问页面
    path('<str:rpath>.html', index_content, name='index_rpath'),
    path('refresh/', get_all_stuinfo_to_tree, name='refresh'),
]

stuOnline/apps/content/models.py
from django.db import models


# 学生表信息
class Student(models.Model):
    id = models.AutoField(primary_key=True)
    stuNo = models.IntegerField(verbose_name='学号', null=False)
    stuName = models.CharField(verbose_name='姓名', max_length=32)
    age = models.IntegerField(verbose_name='年龄')
    gender = models.CharField(verbose_name='性别', max_length=10, choices=(('Female', '女'), ('Male', '男')), null=True)
    nation = models.CharField(verbose_name='民族', max_length=10)
    academy = models.CharField(verbose_name='学院', max_length=20)
    major = models.CharField(verbose_name='专业', max_length=20)
    stuClass = models.CharField(verbose_name='班级', max_length=10)
    stuGrade = models.CharField(verbose_name='年级', max_length=10)

    class Meta:
        verbose_name = '学生信息'
        verbose_name_plural = "学生信息"

    def __str__(self):
        return "[" + str(self.stuNo) + "," + self.stuName + "," + str(self.age) + "," + self.gender + "," \
            + self.nation + "," + self.academy + "," + self.major + "," + self.stuClass + "," + self.stuGrade + "]"


# 数据集分项
class StuInfo(models.Model):
    id = models.AutoField(primary_key=True)
    stuNo = models.IntegerField(verbose_name='学号', null=False)
    stuName = models.CharField(verbose_name='姓名', max_length=32, null=True)
    entrance_score = models.CharField(verbose_name='入学成绩', max_length=10, null=True)
    family_status = models.CharField(verbose_name='家庭状况', max_length=10, null=True)
    attendance = models.CharField(verbose_name='考勤', max_length=10, null=True)
    learn_time = models.IntegerField(verbose_name='每日课后学习时间', null=True)
    grade_point = models.CharField(verbose_name='平均绩点', max_length=10, null=True)
    last_term_score = models.CharField(verbose_name='上学期综合成绩', max_length=10, null=True)
    now_term_score = models.CharField(verbose_name='本学期综合成绩', max_length=10, null=True)
    warning = models.CharField(verbose_name='预警(是/否)', max_length=10, null=True)

    class Meta:
        verbose_name = '数据集'
        verbose_name_plural = "数据集"

    def __str__(self):
        return "[" + self.stuNo + "," + self.stuName + "," + self.entrance_score + "," + self.family_status + "," \
            + self.attendance + "," + self.learn_time + "," + self.grade_point + "," + self.last_term_score + "," \
            + self.now_term_score + "," + self.warning + "]"

stuOnline/apps/content/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .id3 import createTree, classify, storeTree, grabTree, DataSetPredo
from .showtree import createPlot
from django.views.decorators.csrf import csrf_exempt
from .models import StuInfo, Student
import os

# 全局变量
# labels = ['id', '学号', '姓名', '入学成绩', '家庭情况', '考勤', '日常学习时间', '平均绩点', '上学期综合成绩', '本学期综合成绩', '预警']
# 预加载
labels = grabTree(os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'static/labelsStorage.txt'))
decisionTree = grabTree(os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'static/classifierStorage.txt'))


# 匹配主页面局部页面请求
def content_path(request, content_path):
    return render(request, 'content/' + content_path + '.html')


def save_and_show(request):
    pass


# 从内存中读取前端传递的文件数据
@csrf_exempt
def get_file(request):
    if request.method == 'POST':
        file_obj = request.FILES.get('file')
        print(request.FILES)
        print(file_obj, type(file_obj))
        for sentence in file_obj.readlines():
            print(sentence.decode('utf-8', errors='ignore'))
        return JsonResponse({'result': 'ok', 'id': '1400002088'})


# 读取数据库中所有学生记录
def get_all_stu(request):
    stus = Student.objects.values()
    stuList = []
    for stu in stus:
        stuList.append(stu)
    return JsonResponse({"data": stuList})


# 读取数据库中所有训练集数据
def get_all_stuInfo(request):
    stuInfos = StuInfo.objects.values()
    stuInfoList = []
    for stuInfo in stuInfos:
        stuInfoList.append(stuInfo)
    return JsonResponse({"data": stuInfoList})


# 读取前端表单传递的请求分析数据，并返回分析结果
@csrf_exempt
def get_warning_result(request):
    result = "是"
    stuNo = request.POST['stuNo']
    stuName = request.POST['stuName']
    entrance_score = data_to_pred(request.POST['entrance_score'])
    family_status = request.POST['family_status']
    attendance = request.POST['attendance']
    learn_time = learn_time_pred(request.POST['learn_time'])
    grade_point = gradepoint_to_pred(request.POST['grade_point'])
    last_term_score = data_to_pred(request.POST['last_term_score'])
    now_term_score = data_to_pred(request.POST['now_term_score'])
    print(entrance_score, family_status, attendance, learn_time, grade_point, last_term_score, now_term_score)
    stuinfo = [entrance_score, family_status, attendance, learn_time, grade_point, last_term_score, now_term_score]
    # stuinfo = ['B', 'Average', 'Good', '2', 'C', 'C', 'C']
    result = classify(decisionTree, labels, stuinfo)
    print(result)
    return JsonResponse({'result': result})


# 前端数据预处理
def data_to_pred(scoreStr):
    score = int(scoreStr)
    if score < 60:
        return 'D'
    elif score < 75:
        return 'C'
    elif score < 90:
        return 'B'
    else:
        return 'A'

# 绩点处理
def gradepoint_to_pred(points):
    gradepoint = float(points)
    if gradepoint < 2.5:
        return 'D'
    elif gradepoint < 3.5:
        return 'C'
    elif gradepoint < 4.5:
        return 'B'
    else:
        return 'A'

def learn_time_pred(times):
    times = float(times)
    if times < 4:
        return times
    else:
        return 0


# 从数据库读取所有数据生成决策树
def get_all_stuinfo_to_tree(request):
    stuInfos = StuInfo.objects.all()
    dataset = []
    for stuinfo in stuInfos:
        stu = []
        # stu.append(stuinfo.id)
        # stu.append(stuinfo.stuNo)
        # stu.append(stuinfo.stuName)
        stu.append(stuinfo.entrance_score)
        stu.append(stuinfo.family_status)
        stu.append(stuinfo.attendance)
        stu.append(stuinfo.learn_time)
        stu.append(stuinfo.grade_point)
        stu.append(stuinfo.last_term_score)
        stu.append(stuinfo.now_term_score)
        stu.append(stuinfo.warning)
        dataset.append(stu)
    label = ['入学成绩', '家庭情况', '考勤', '日常学习时间', '平均绩点', '上学期综合成绩', '本学期综合成绩']
    weight = [1.0 for i in range(len(dataset))]
    dataset, label = DataSetPredo(dataset, label, [3])
    storeTree(label, os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'static/labelsStorage.txt'))
    tree = createTree(dataset, weight, label)
    createPlot(tree)
    storeTree(tree, os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'static/classifierStorage.txt'))
    return JsonResponse({'result': decisionTree})



# 从txt文件读取数据并导入数据库
def readAndSaveStu(request):
    filename = os.path.join(os.path.dirname(__file__), 'stuinfo.txt')
    with open(filename, 'r') as fr:
        for line in fr.readlines():
            # arr = line.split(',')
            arr = line.strip('\n\n').split(',')
            stu = Student.objects.get_or_create(stuNo=arr[0], stuName=arr[1], age=arr[2], gender=arr[3], nation=arr[4], academy=arr[5], major=arr[6], stuClass=arr[7], stuGrade=arr[8])
            print(stu)
    return JsonResponse(filename, safe=False)


# 从txt文件读取数据并导入数据库
def readAndSaveInfo(request):
    filename = os.path.join(os.path.dirname(__file__), 'stuResult.txt')
    with open(filename, 'r') as fr:
        for line in fr.readlines():
            arr = line.strip('\n').split(',')
            stuinfo = StuInfo.objects.get_or_create(stuNo=arr[1], stuName=arr[2], entrance_score=arr[3], family_status=arr[4], \
                                          attendance=arr[5], learn_time=arr[6], grade_point=arr[7], \
                                          last_term_score=arr[8], now_term_score=arr[9], warning=arr[10])
            print(stuinfo)
    return JsonResponse(filename, safe=False)


# def stu_get_or_create(arr):
#     Student.objects.get_or_create(stuNo=arr[0], stuName=arr[1], age=arr[2], gender=arr[3], nation=arr[4],
#                                   academy=arr[5], major=arr[6], stuClass=arr[7], stuGrade=arr[8])

# if __name__ == '__main__':
#     dataset, labels = DataSetPredo('xigua.txt', [0, 1, 2, 3, 4, 5, 6, 7, 8])
#     print(labels)
#     weight = [1.0 for i in range(len(dataset))]
#     myTree = createTree(dataset[:100], weight, labels)
#     # myTree = createTree(dataset[:100], labels, dataset_full, labels_full)
#     print(myTree)
#     createPlot(myTree)
#     i = 1
#     cnt = 0
#     for lis in dataset[100:]:
#         judge = classify(myTree, labels, lis[:-1])
#         target = lis[-1]
#         if judge == target:
#             cnt += 1
#         print("Test %d was classified %s, it's class is %s %s" % (i, judge, target, "=====" if judge == target else ""))
#         i += 1
#     print("The Tree's Accuracy is %.3f" % (cnt / float(i)))

stuOnline/apps/content/templates/content/dataAnalysis.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static '/css/datatables.css' %}">
    <link rel="stylesheet" href="{% static '/bootstrap-4.1.0/css/bootstrap.min.css' %}">
    <!-- <link rel="stylesheet" href="../../../../static/bootstrap-4.1.0/css/bootstrap.min.css"> -->
    <title>Data Analysis</title>
</head>
<body>
    <div class="container">
        <div class="mt-3 border rounded">
            <!-- tab header -->
            <ul class="nav nav-tabs" id="mytab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="nav-single-tab" data-toggle="tab" href="#single" role="tab" aria-controls="single" aria-selected="true">数据录入</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="nav-batch-tab" data-toggle="tab" href="#batch" role="tab" aria-controls="batch" aria-selected="false">批量分析</a>
                </li>
            </ul>
            <!-- tab pane -->
            <div class="tab-content" id="dataContent">
                <!-- single-analysis -->
                <div class="tab-pane fade show active" id="single" role="tabpanel" aria-labelledby="nav-single-tab">
                    <div class="card">
                        <div class="card-header">学生学业信息预警分析</div>
                        <div class="card-body">
                            <form id="infoForm" onsubmit="return false">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text mr-2" id="sNo">学号</span>
                                    </div>
                                    <input type="text" name="stuNo" id="stuNo" placeholder="例如: 1400002088" aria-describedby="sNo">
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text mr-2" id="sName">姓名</span>
                                    </div>
                                    <input type="text" name="stuName" id="stuName" placeholder="例如: 张三" aria-describedby="sName">
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text mr-2" id="sScore">入学成绩</span>
                                    </div>
                                    <input type="text" name="entrance_score" id="entrance_score" placeholder="输入范围: 0 ~ 100之间" aria-describedby="sScore" required>
                                </div>
                                <div class="form-group">                       
                                    <label>家庭状况</label><br>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="family_status" id="family_status1" value="Poor">
                                        <label class="form-check-label" for="family_status1">
                                            困难
                                        </label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="family_status" id="family_status2" value="Average" checked="checked">
                                        <label class="form-check-label" for="family_status2">
                                            普通
                                        </label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="family_status" id="family_status3" value="Good">
                                        <label class="form-check-label" for="family_status3">
                                            富裕
                                        </label>
                                    </div>
                                </div>
                                <div class="form-group">                       
                                    <label>考勤</label><br>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="attendance" id="attendance1" value="Poor">
                                        <label class="form-check-label" for="family_status1">
                                            极差
                                        </label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="attendance" id="attendance2" value="Average" checked="checked">
                                        <label class="form-check-label" for="family_status2">
                                            一般
                                        </label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="attendance" id="attendance3" value="Good">
                                        <label class="form-check-label" for="family_status3">
                                            优秀
                                        </label>
                                    </div>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text mr-2" id="sLearn">日常学习时间</span>
                                    </div>
                                    <input type="text" name="learn_time" id="learn_time" aria-describedby="sLearn" required>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text mr-2" id="sPoint">平均绩点</span>
                                    </div>
                                    <input type="text" name="grade_point" id="grade_point" aria-describedby="sPoint" placeholder="例如: 3.6" required>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text mr-2" id="sLScore">上学期综合成绩</span>
                                    </div>
                                    <input type="text" name="last_term_score" id="last_term_score" aria-describedby="sLScore" placeholder="输入范围: 0 ~ 100之间" required>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text mr-2" id="sNScore">本学期综合成绩</span>
                                    </div>
                                    <input type="text" name="now_term_score" id="now_term_score" aria-describedby="sNScore" placeholder="输入范围: 0 ~ 100之间" required>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text mr-2" id="mess">学生学业预测结果：</span>
                                    </div>
                                    <span class="text-danger" id="message" aria-describedby="mess"></span>
                                </div>
                                <div class="form-group">
                                    <button id="analysis" type="button" class="btn btn-lg btn-primary btn-block">预测</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- batch-analysis -->
                <div class="tab-pane fade" id="batch" role="tabpanel" aria-labelledby="nav-batch-tab">
                    <!-- <div class="card">
                        <div class="card-header">学生信息批量处理</div>
                        <div class="card-body">
                            <form>

                            </form>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </div>




    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/bootstrap-4.1.0/js/bootstrap.min.js' %}"></script>
    <!-- <script src="../../../../static/js/jquery-3.3.1.min.js"></script> -->
    <!-- <script src="../../../../static/bootstrap-4.1.0/js/bootstrap.min.js"></script> -->
    <script>
        $(document).ready(function(){
            $('#analysis').click(function(){
                $.ajax({
                    type: "POST",
                    url: "{% url 'content:get_warning_result' %}",
                    data: $('#infoForm').serialize(),
                    dataType: "json",
                    success: function(msg){
                        results = msg['result']
                        if(results == '是')
                            $('#message').html("预警,需要注意该学生学业状况。")
                        else
                            $('#message').html("该学生学业正常。")
                    },
                    error: function(){
                        alert("请完整输入所有值！")
                    }
                })
            });
        });
    </script>
</body>
</html>

stuOnline/apps/content/templates/content/decisionData.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static '/css/datatables.css' %}">
    <link rel="stylesheet" href="{% static '/bootstrap-4.1.0/css/bootstrap.min.css' %}">
    <title>DataTables</title>
</head>
<body>
    <div class="container-fluid">
        <div class="mt-3">
            <table id="table_id" class="table table-hover" width="100%">
                <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">学号</th>
                        <th scope="col">姓名</th>
                        <th scope="col">入学成绩</th>
                        <th scope="col">家庭状况</th>
                        <th scope="col">考勤</th>
                        <th scope="col">日常学时</th>
                        <th scope="col">平均绩点</th>
                        <th scope="col">上学期综合成绩</th>
                        <th scope="col">本学期综合成绩</th>
                        <th scope="col">预警(是/否)</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>



    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/js/datatables.js' %}"></script>
    <script src="{% static '/bootstrap-4.1.0/js/bootstrap.min.js' %}"></script>
    <script>
        $(document).ready(function(){
            $('#table_id').DataTable({
                language: {
                    "sZeroRecords": "没有匹配结果",
                    "sLengthMenu": "显示 _MENU_ 项结果",
                    "sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
                    "sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
                    "sSearch": "搜索:",
                    "sInfoFiltered": "(从 _MAX_ 项结果中过滤)"
                },
                // data: data
                ajax: {
                    url: "{% url 'content:get_all_stuInfo' %}",
                    type: 'GET'
                },
                columns: [
                    {data: 'id'},
                    {data: 'stuNo'},
                    {data: 'stuName'},
                    {data: 'entrance_score'},
                    {data: 'family_status'},
                    {data: 'attendance'},
                    {data: 'learn_time'},
                    {data: 'grade_point'},
                    {data: 'last_term_score'},
                    {data: 'now_term_score'},
                    {data: 'warning'}
                ]
            });

        });
    </script>
</body>
</html>

stuOnline/apps/content/templates/content/stuInfo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static '/css/datatables.css' %}">
    <link rel="stylesheet" href="{% static '/bootstrap-4.1.0/css/bootstrap.min.css' %}">
    <title>StudentInfo</title>
</head>
<body>
    <div class="container-fluid">
        <div class="mt-3">
            <table id="table_id" class="table table-hover" width="100%">
                <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">学号</th>
                        <th scope="col">姓名</th>
                        <th scope="col">年龄</th>
                        <th scope="col">性别</th>
                        <th scope="col">民族</th>
                        <th scope="col">学院</th>
                        <th scope="col">专业</th>
                        <th scope="col">班级</th>
                        <th scope="col">年级</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>

    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/js/datatables.js' %}"></script>
    <script src="{% static '/bootstrap-4.1.0/js/bootstrap.min.js' %}"></script>
    <script>
        $(document).ready(function(){
            $('#table_id').DataTable({
                language: {
                    "sZeroRecords": "没有匹配结果",
                    "sLengthMenu": "显示 _MENU_ 项结果",
                    "sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
                    "sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
                    "sSearch": "搜索:",
                    "sInfoFiltered": "(从 _MAX_ 项结果中过滤)"
                },
                // data: data
                ajax: {
                    url: "{% url 'content:get_stu' %}",
                    type: 'GET'
                },
                columns: [
                    {data: 'id'},
                    {data: 'stuNo'},
                    {data: 'stuName'},
                    {data: 'age'},
                    {data: 'gender'},
                    {data: 'nation'},
                    {data: 'academy'},
                    {data: 'major'},
                    {data: 'stuClass'},
                    {data: 'stuGrade'},
                ]
            });

        });
    </script>
</body>
</html>